name: Build and Push Directus Docker Image

on:
  push:
    branches: [ main ]  # Тільки main, develop видалено
    paths:
      - 'Dockerfile'
      - 'extensions/**'
      - '.github/workflows/directus-docker.yml'
  workflow_dispatch:  # Можливість запуску вручну

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      # Тег тільки latest для продакшн Directus
      - name: Build and push Directus Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/directus:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/directus:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/directus:buildcache,mode=max
          platforms: linux/amd64,linux/arm64